AWSTemplateFormatVersion: 2010-09-09
Parameters:
  ProjectId:
    Type: String
    Description: AWS CodeStar projectID used to associate new resources to team members
Resources:
  GetDashboard:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        S3Bucket: aws-codestar-us-west-2-532376259100-homecontrol-pipe
        S3Key: edfc0e073a2b920c51367a76a7ca7017
      Handler: index.get
      Role: !ImportValue
        'Fn::Join':
          - '-'
          - - !Ref ProjectId
            - !Ref 'AWS::Region'
            - LambdaTrustRole
      Runtime: nodejs4.3
      Tags:
        - Value: SAM
          Key: 'lambda:createdBy'
  ServerlessRestApiDeployment3f02761397:
    Type: 'AWS::ApiGateway::Deployment'
    Properties:
      RestApiId: !Ref ServerlessRestApi
      Description: 'RestApi deployment id: 3f02761397b356f46b53ec0cdba71d55841c07e9'
      StageName: Stage
  ServerlessRestApiProdStage:
    Type: 'AWS::ApiGateway::Stage'
    Properties:
      DeploymentId: !Ref ServerlessRestApiDeployment3f02761397
      RestApiId: !Ref ServerlessRestApi
      StageName: Prod
  GetDashboardGetEventPermissionProd:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:invokeFunction'
      Principal: apigateway.amazonaws.com
      FunctionName: !Ref GetDashboard
      SourceArn: !Sub
        - >-
          arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${__ApiId__}/${__Stage__}/GET/
        - __Stage__: Prod
          __ApiId__: !Ref ServerlessRestApi
  GetDashboardGetEventPermissionTest:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:invokeFunction'
      Principal: apigateway.amazonaws.com
      FunctionName: !Ref GetDashboard
      SourceArn: !Sub
        - >-
          arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${__ApiId__}/${__Stage__}/GET/
        - __Stage__: '*'
          __ApiId__: !Ref ServerlessRestApi
  ServerlessRestApi:
    Type: 'AWS::ApiGateway::RestApi'
    Properties:
      Body:
        info:
          version: '1.0'
          title: !Ref 'AWS::StackName'
        paths:
          /:
            get:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub >-
                  arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetDashboard.Arn}/invocations
              responses: {}
        swagger: '2.0'
  SyncResources1528728297480:
    DependsOn:
      - GetDashboard
      - ServerlessRestApiDeployment3f02761397
      - ServerlessRestApiProdStage
      - GetDashboardGetEventPermissionProd
      - GetDashboardGetEventPermissionTest
      - ServerlessRestApi
    Type: 'AWS::CodeStar::SyncResources'
    Properties:
      ProjectId: !Ref ProjectId
